//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysAgropec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Aplicacao_Medicamento = new HashSet<Aplicacao_Medicamento>();
            this.Producao = new HashSet<Producao>();
        }
    
        public int ID { get; set; }
        public string Descricao { get; set; }
        public string Registro { get; set; }
        public string Tatuagem { get; set; }
        public Nullable<int> Numerobrinco { get; set; }
        public Nullable<System.DateTime> Datanascimento { get; set; }
        public Nullable<sbyte> Morto { get; set; }
        public string Observacao { get; set; }
        public System.DateTime Datacadastro { get; set; }
        public Nullable<System.DateTime> Datalteracao { get; set; }
        public string Registropai { get; set; }
        public string Tatuagempai { get; set; }
        public string Descricaopai { get; set; }
        public string Registromae { get; set; }
        public string Tatuagemae { get; set; }
        public string Descricaomae { get; set; }
        public Nullable<int> Sexo { get; set; }
        public Nullable<sbyte> Lactacao { get; set; }
        public Nullable<int> Dias_lactacao { get; set; }
        public Nullable<System.DateTime> Datalactacao { get; set; }
        public int Livro_ID { get; set; }
        public int Raca_ID { get; set; }
        public int Propriedade_ID { get; set; }
        public int Usuario_IDCadastro { get; set; }
        public Nullable<int> Usuario_IDAlteracao { get; set; }
    
        public virtual Livro Livro { get; set; }
        public virtual Propriedade Propriedade { get; set; }
        public virtual Raca Raca { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aplicacao_Medicamento> Aplicacao_Medicamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producao> Producao { get; set; }
    }
}
