//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysAgropec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estoque_Medicamento
    {
        public int ID { get; set; }
        public Nullable<int> Quantidademinima { get; set; }
        public Nullable<int> Quantidademaxima { get; set; }
        public Nullable<int> Quantidadeatual { get; set; }
        public int Medicamento_ID { get; set; }
        public Nullable<int> Usuario_IDAlteracao { get; set; }
        public System.DateTime Data_Estocado { get; set; }
    
        public virtual Medicamento Medicamento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
