//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysAgropec.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sysagropecEntitiesAzure : DbContext
    {
        public sysagropecEntitiesAzure()
            : base("name=sysagropecEntitiesAzure")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<animal> animal { get; set; }
        public virtual DbSet<aplicacao_medicamento> aplicacao_medicamento { get; set; }
        public virtual DbSet<estoque_medicamento> estoque_medicamento { get; set; }
        public virtual DbSet<livro> livro { get; set; }
        public virtual DbSet<lote> lote { get; set; }
        public virtual DbSet<medicamento> medicamento { get; set; }
        public virtual DbSet<producao> producao { get; set; }
        public virtual DbSet<propriedade> propriedade { get; set; }
        public virtual DbSet<raca> raca { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
