//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysAgropec.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sysagropecConnection : DbContext
    {
        public sysagropecConnection()
            : base("name=sysagropecConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Aplicacao_Medicamento> Aplicacao_Medicamento { get; set; }
        public virtual DbSet<Estoque_Medicamento> Estoque_Medicamento { get; set; }
        public virtual DbSet<Livro> Livro { get; set; }
        public virtual DbSet<Lote> Lote { get; set; }
        public virtual DbSet<Medicamento> Medicamento { get; set; }
        public virtual DbSet<Producao> Producao { get; set; }
        public virtual DbSet<Propriedade> Propriedade { get; set; }
        public virtual DbSet<Raca> Raca { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
